version: "3"

services:
  web:
    restart: always
    image: poc-redis:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:80"
    networks:
      - redis-network
    depends_on:
      - "redisdb"


  redisdb:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - redis-network

networks: 
    redis-network:
        driver: bridge